name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for your interest in AlgoPlus, a maintainer will see your issue soon!"
        pr-message: "Thank you for your interest in AlgoPlus, a maintainer will see your PR soon!"
